---
- name: Check if Helm binary exists.
  stat:
    path: "{{ helm_bin_path }}"
  register: helm_check

- name: Check current helm version
  ansible.builtin.command: >-
    {{ helm_bin_path }}/helm version --client --template
    {{ "'{{ if .Version }}{{ .Version }}{{ else }}{{ .Client.SemVer }}{{ end }}'" }}
  register: helm_installed_version
  failed_when: false
  changed_when: false

- name: Install helm.
  ansible.builtin.import_tasks: tasks/install_helm.yml
  when: >
    not helm_check.stat.exists
    or helm_installed_version.rc != 0
    or helm_installed_version.stdout != ('v' + helm_version)
